apiVersion: batch/v1
kind: Job
metadata:
  name: datahub-upgrade
spec:
  template:
    spec:
      containers:
        - name: datahub-upgrade
          image: acryldata/datahub-upgrade:head
          args:
            - -u
            - SystemUpdate
          env:
          - name: BACKFILL_BROWSE_PATHS_V2
            value: "true"
          - name: DATAHUB_GMS_HOST
            value: datahub-gms
          - name: DATAHUB_GMS_PORT
            value: "8080"
          - name: EBEAN_DATASOURCE_DRIVER
            value: com.mysql.jdbc.Driver
          - name: EBEAN_DATASOURCE_HOST
            value: mysql:3306
          - name: EBEAN_DATASOURCE_PASSWORD
            value: datahub
          - name: EBEAN_DATASOURCE_URL
            value: jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
          - name: EBEAN_DATASOURCE_USERNAME
            value: datahub
          - name: ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES
            value: "false"
          - name: ELASTICSEARCH_HOST
            value: elasticsearch
          - name: ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX
            value: "true"
          - name: ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX
            value: "true"
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: ENTITY_REGISTRY_CONFIG_PATH
            value: /datahub/datahub-gms/resources/entity-registry.yml
          - name: GRAPH_SERVICE_IMPL
            value: elasticsearch
          - name: KAFKA_BOOTSTRAP_SERVER
            value: kafka:9092
          # - name: KAFKA_SCHEMAREGISTRY_URL
          #   value: http://schema-registry:8081
          - name: REPROCESS_DEFAULT_BROWSE_PATHS_V2
            value: "false"
      restartPolicy: Never
  backoffLimit: 4
---


